[dev]
    command = "npm run start"
    [dev.https]
        keyFile = ".certificados/local.florenciodelgadogurriaran.gal-key.pem"
        certFile = ".certificados/local.florenciodelgadogurriaran.gal.pem"

    
[build]
    publish = "_site"
    command = "npm run build"

[[redirects]]
    from = "/"
    to = "/dicionario"
    # Redirección temporal
    status = 302
    # Redirigimos aunque haya contenido en la carpeta
    force = true
    
[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200